ALTER TABLE laboratorio.EXPEDIENTE_LABORATORIO MODIFY no_registro BIGINT(20) NOT NULL;
ALTER TABLE laboratorio.EXPEDIENTE_LABORATORIO MODIFY id_paciente int(20);
ALTER TABLE laboratorio.EXPEDIENTE_LABORATORIO MODIFY fecha_nacimiento datetime;
ALTER TABLE laboratorio.EXPEDIENTE_LABORATORIO MODIFY direccion varchar(300);
ALTER TABLE laboratorio.EXPEDIENTE_LABORATORIO MODIFY telefono varchar(50);
ALTER TABLE laboratorio.EXPEDIENTE_LABORATORIO MODIFY movil varchar(50);
ALTER TABLE laboratorio.EXPEDIENTE_LABORATORIO MODIFY email varchar(80);
ALTER TABLE laboratorio.EXPEDIENTE_LABORATORIO MODIFY sexo varchar(50);
